# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_password_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.currentPasswordLabel = QtWidgets.QLabel(Form)
        self.currentPasswordLabel.setObjectName("currentPasswordLabel")
        self.verticalLayout.addWidget(self.currentPasswordLabel)
        self.currentPasswordLineEdit = QtWidgets.QLineEdit(Form)
        self.currentPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.currentPasswordLineEdit.setObjectName("currentPasswordLineEdit")
        self.verticalLayout.addWidget(self.currentPasswordLineEdit)
        self.newPasswordLabel = QtWidgets.QLabel(Form)
        self.newPasswordLabel.setObjectName("newPasswordLabel")
        self.verticalLayout.addWidget(self.newPasswordLabel)
        self.newPasswordLineEdit = QtWidgets.QLineEdit(Form)
        self.newPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newPasswordLineEdit.setObjectName("newPasswordLineEdit")
        self.verticalLayout.addWidget(self.newPasswordLineEdit)
        self.confirmPasswordLabel = QtWidgets.QLabel(Form)
        self.confirmPasswordLabel.setObjectName("confirmPasswordLabel")
        self.verticalLayout.addWidget(self.confirmPasswordLabel)
        self.confirmPasswordLineEdit = QtWidgets.QLineEdit(Form)
        self.confirmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordLineEdit.setObjectName("confirmPasswordLineEdit")
        self.verticalLayout.addWidget(self.confirmPasswordLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.changePasswordButton = QtWidgets.QPushButton(Form)
        self.changePasswordButton.setObjectName("changePasswordButton")
        self.verticalLayout.addWidget(self.changePasswordButton)
        self.waitLabel = QtWidgets.QLabel(Form)
        self.waitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.waitLabel.setObjectName("waitLabel")
        self.verticalLayout.addWidget(self.waitLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleLabel.setText(_translate("Form", "Change Password"))
        self.currentPasswordLabel.setText(_translate("Form", "Current Password"))
        self.newPasswordLabel.setText(_translate("Form", "New Password"))
        self.confirmPasswordLabel.setText(_translate("Form", "Confirm New Password"))
        self.changePasswordButton.setText(_translate("Form", "Change"))
        self.waitLabel.setText(_translate("Form", "Please wait ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
