# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sessions_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(483, 498)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.sessionTimeLabel = QtWidgets.QLabel(self.groupBox_8)
        self.sessionTimeLabel.setText("")
        self.sessionTimeLabel.setObjectName("sessionTimeLabel")
        self.horizontalLayout_7.addWidget(self.sessionTimeLabel)
        self.endSessionButton = QtWidgets.QPushButton(self.groupBox_8)
        self.endSessionButton.setObjectName("endSessionButton")
        self.horizontalLayout_7.addWidget(self.endSessionButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.endSessionButton.raise_()
        self.sessionTimeLabel.raise_()
        self.verticalLayout.addWidget(self.groupBox_8)
        self.sessionFrame = QtWidgets.QFrame(Form)
        self.sessionFrame.setStyleSheet("")
        self.sessionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sessionFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sessionFrame.setObjectName("sessionFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.sessionFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.widget = QtWidgets.QWidget(self.sessionFrame)
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.startSessionButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.startSessionButton.setFont(font)
        self.startSessionButton.setAutoExclusive(True)
        self.startSessionButton.setObjectName("startSessionButton")
        self.horizontalLayout_6.addWidget(self.startSessionButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_5.addWidget(self.widget)
        self.label_6 = QtWidgets.QLabel(self.sessionFrame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.sessionFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.endSessionButton.setText(_translate("Form", "End Session"))
        self.startSessionButton.setText(_translate("Form", "Start Session"))
        self.label_6.setText(_translate("Form", "Start a session to start selling products"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
